export PATH=$PATH:$HOME/bin:/usr/local/bin:/home/sole/.emacs.d/bin
export PATH=$PATH:$HOME/apps:$HOME/apps/Zotero_linux-x86_64/:$HOME/apps/myScripts
export TERMINAL=termite
export OOO_FORCE_DESKTOP=gnome soffice
export BROWSER='google-chrome-stable'
export PAGER=less
export EDITOR=vim
export LESS='-R'
export HISTCONTROL=ignoredups
export HISTSIZE=5000
export HISTFILESIZE=1000
export HISTIGNORE="&:ls:ll:la:l.:pwd:exit:clear"
export SANE_DEFAULT_DEVICE="brother4:bus4;dev3"
LESSOPEN="|lesspipe.sh %s"; export LESSOPEN
export PYSPARK_SUBMIT_ARGS="--master local[2] pyspark-shell"
export JAVA_HOME="/usr/bin/java"
export PROJECT_HOME=$HOME/apps/
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
export TERMINAL=termite
export TERM=xterm-256color
export QT_STYLE_OVERRIDE=gtk
export QT_SELECT=qt5

